### ISSUE TITLE
[TAREFA] Ajustar critérios de aceitação

### ISSUE THREAD

**Issue by luciano-freitas-melo** [mdsreq-fga-unb/2023-2-BeachTennisCoordiMate#63]
- [x] Colocar critérios que está na documentação nas issues
- [x] Alterar critérios no pages da #45 para ficar igual o que tem na issue
- [x] Colocar últimos dois critérios da #47 para a issue #51 e alterar no pages
- [x] Modificar o primeiro critério da #47 para que seja só o título que o usuário deve fornecer as infos e criar outro critério que o sistema deve criar os campos de objetivos e observações vazios
